version: "3.8"
services:
  db:
    build: ./mariaDB
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    restart: unless-stopped
    networks:
      - hang-out-network
    volumes:
      - ./mariaDB/data:/var/lib/mysql

  backend:
    build: ./backend-hang-out
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - hang-out-network

networks:
  hang-out-network:
    driver: bridge


